modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[dependencies.ror]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[mods]]
    modId="ror"
    version="${file.jarVersion}"
    displayName="RoR"
    description='''
        RoR - Ruins of Realms
    '''
    logoFile="logo.png"
    authors="acth2"

[[dependencies.ror]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.106,)"
    ordering="NONE"
    side="BOTH"