modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[dependencies.ror]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[mods]]
    modId="ror"
    version="${file.jarVersion}"
    displayName="RoR"
    description='''
        RoR - Ruins of Realms
    '''
    logoFile="logo.png"
    authors="acth2"
    displayURL="https://github.com/acth2/ror"

[[dependencies.ror]]
    modId="geckolib"
    mandatory=true
    versionRange="[3.0.106,)"
    ordering="NONE"
    side="BOTH"